### ISSUE TITLE
Where to set AzureSignalR connection string?

### ISSUE THREAD

**Issue by emVdovin** [aspnet/AzureSignalR-samples#7]
In ChatRoom sample, where to set the connection string?

Is there an example to connect from .Net framework 4.6 client?

Thanks!

**Comment by robertmclaws** [comment]
The current instructions are not working on Azure WebApps.

**Comment by xscript** [comment]
@robermclaw use `Azure__SignalR__ConnectionString` as appsettings key in Azure WebApp.

**Comment by robertmclaws** [comment]
I'm using that and it is still throwing an error. See this thread: https://twitter.com/chenkennt/status/1007511818518986753

**Comment by BrennanConroy** [comment]
What's your program.cs look like? If you don't have environment variables hooked up that could explain why it isn't working.

**Comment by davidfowl** [comment]
@xscript were you testing on webapp for containers or Azure App Service (on windows)?

**Comment by xscript** [comment]
I remembered both of them worked with `Azure__SignalR__ConnectionString`. But let me double confirm on App Service on Windows.

**Comment by robertmclaws** [comment]
Thanks for your help everyone, I confirmed it was because I had it in the "ConnectionStrings" section instead of the AppSettings sections.

I think calling it a "ConnectionString" might be problematic. I made this mistake coming from 4+ years deploying classic ASP.NET apps into Azure WebApps, and putting Storage & WebJob ConnectionStrings in the ConnectionStrings section in Azure. I might be the only person that will ever make that mistake, but I don't think so.

I think the options would be to:
1) Create the concept of a ConnectionStrings section in ASP.NET Core so that they map to other Azure systems & .NET apps.
2) Change the name of the variable so it doesn't use the words "connection string" in it.
3) Rename the current documentation [here](https://github.com/aspnet/AzureSignalR-samples/blob/master/docs/azure-integration.md) to refer to Azure Containers, and create a new doc about Azure Websites, clearly delineating (with screenshots) NOT to put the setting in the ConnectionStrings section.

Some combination of 2 & 3 would probably be best, IMHO. Thanks again!

**Comment by xscript** [comment]
Thanks for the suggestions.

We will definitely refine the documentation to make things clearer.

Regarding option#1, ASP.NET Core do provide an API for getting connection string specifically. The API documentation is [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationextensions.getconnectionstring?view=aspnetcore-2.1#Microsoft_Extensions_Configuration_ConfigurationExtensions_GetConnectionString_Microsoft_Extensions_Configuration_IConfiguration_System_String_).
Regarding option#2, I think we can add the `ConnectionStrings` section into the fallback path when trying to loading the connection string from enviroment. I've created https://github.com/Azure/azure-signalr/issues/126 to track this. You can follow up from there.
